export const members = [
  {
    year: 2025,
    name: "Nisal Perera",
    imageUrl: "/images/excom/2025/nisal-perera.jpg",
    title: "Chair",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2025,
    name: "Kavindu Kavishka",
    imageUrl: "/images/excom/2025/kavindu-kavishka.jpg",
    title: "Vice Chair",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2025,
    name: "Dinuka Jayawardana",
    imageUrl: "/images/excom/2025/dinuka-jayawardana.jpg",
    title: "Secretary",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2025,
    name: "Kavindu Kavishka",
    imageUrl: "/images/excom/2025/kavindu-kavishka.jpg",
    title: "Treasurer",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2025,
    name: "Dinuka Jayawardana",
    imageUrl: "/images/excom/2025/dinuka-jayawardana.jpg",
    title: "Vice Chair",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2024,
    name: "Nisal Perera",
    imageUrl: "/images/excom/2025/nisal-perera.jpg",
    title: "Chair",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2024,
    name: "Kavindu Kavishka",
    imageUrl: "/images/excom/2025/kavindu-kavishka.jpg",
    title: "Vice Chair",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2024,
    name: "Dinuka Jayawardana",
    imageUrl: "/images/excom/2025/dinuka-jayawardana.jpg",
    title: "Secretary",
    linkdInURL: "",
    facebookURL: "",
  },
  {
    year: 2024,
    name: "Kavindu Kavishka",
    imageUrl: "/images/excom/2025/kavindu-kavishka.jpg",
    title: "Treasurer",
    linkdInURL: "",
    facebookURL: "",
  },
];
